# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date_time', models.DateTimeField()),
                ('event_location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selectfood.Food'),
        ),
    ]
